services:
  backend:
    build:
      context: ./backend

    container_name: asistencia-backend

    ports:
      - "3000:3000"
    
    volumes:
      - ./volumes/sqlite:/data
    
    environment:
      DB_PATH: /data/database.sqlite

    restart: unless-stopped
